### ISSUE TITLE
IP address in azuredeploy.json

### ISSUE THREAD

**Issue by samchivers** [ans-group/azure-qna-bot#1]
https://github.com/ans-group/azure-qna-bot/blob/60679b6ad699acff44958656a70ae869e0aecf9c/template/azuredeploy.json#L212

Hi, just wondering whether this IP address has been included in the template by mistake?

**Comment by nathanguk** [comment]
Found it a couple of days ago it needs to be removed

Sent from my iPhone

On 21 Apr 2020, at 17:13, Sam Chivers <notifications@github.com> wrote:

﻿

https://github.com/ans-group/azure-qna-bot/blob/60679b6ad699acff44958656a70ae869e0aecf9c/template/azuredeploy.json#L212<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fans-group%2Fazure-qna-bot%2Fblob%2F60679b6ad699acff44958656a70ae869e0aecf9c%2Ftemplate%2Fazuredeploy.json%23L212&data=02%7C01%7C%7Cab35d241b878474e828608d7e60eec65%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637230824071501694&sdata=4pV4RnUJyvRZyJKUDoanqPmmGGTaC5BM4JddfXm1%2B1E%3D&reserved=0>

Hi, just wondering whether this IP address has been included in the template by mistake?

**Comment by nathanguk** [comment]
Removed it now

Sent from my iPhone

On 21 Apr 2020, at 17:13, Sam Chivers <notifications@github.com> wrote:

﻿

https://github.com/ans-group/azure-qna-bot/blob/60679b6ad699acff44958656a70ae869e0aecf9c/template/azuredeploy.json#L212<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fans-group%2Fazure-qna-bot%2Fblob%2F60679b6ad699acff44958656a70ae869e0aecf9c%2Ftemplate%2Fazuredeploy.json%23L212&data=02%7C01%7C%7Cab35d241b878474e828608d7e60eec65%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637230824071501694&sdata=4pV4RnUJyvRZyJKUDoanqPmmGGTaC5BM4JddfXm1%2B1E%3D&reserved=0>

Hi, just wondering whether this IP address has been included in the template by mistake?

**Comment by samchivers** [comment]
Great, thanks for confirming
